/** Prefixos montados em `app.ts` → tag e descrição para OpenAPI. */
export interface ApiMount {
  prefix: string;
  tag: string;
  description: string;
  routeFile?: string;
}

export const API_MOUNTS: ApiMount[] = [
  { prefix: '/api/health', tag: 'Sistema', description: 'Health check da API' },
  { prefix: '/api/auth', tag: 'Autenticação', description: 'Login, registro e recuperação de senha', routeFile: 'auth.ts' },
  { prefix: '/api/protected', tag: 'Protegido', description: 'Rotas de teste autenticadas', routeFile: 'protected.routes.ts' },
  { prefix: '/api/materiais', tag: 'Materiais', description: 'Catálogo de materiais e estoque', routeFile: 'materiais.ts' },
  { prefix: '/api/brasil-api', tag: 'Brasil API', description: 'Consultas NCM e dados auxiliares', routeFile: 'brasilApiNcm.routes.ts' },
  { prefix: '/api/compras', tag: 'Compras', description: 'Notas de compra e fracionamento', routeFile: 'compras.ts' },
  { prefix: '/api/orcamentos', tag: 'Orçamentos', description: 'Propostas comerciais e PDF', routeFile: 'orcamentos.ts' },
  { prefix: '/api/vendas', tag: 'Vendas', description: 'Pedidos de venda e contas a receber', routeFile: 'vendas.routes.ts' },
  { prefix: '/api/contas-pagar', tag: 'Contas a Pagar', description: 'Financeiro — despesas', routeFile: 'contasPagar.routes.ts' },
  { prefix: '/api/contas-receber', tag: 'Contas a Receber', description: 'Financeiro — receitas', routeFile: 'contasReceber.routes.ts' },
  { prefix: '/api/relatorios', tag: 'Relatórios', description: 'Exportações e relatórios', routeFile: 'relatorios.routes.ts' },
  { prefix: '/api/configuracoes-fiscais', tag: 'Config. Fiscal', description: 'Parâmetros fiscais', routeFile: 'configFiscal.ts' },
  { prefix: '/api/obras', tag: 'Obras', description: 'Execução, tarefas e alocações', routeFile: 'obra.routes.ts' },
  { prefix: '/api/equipes', tag: 'Equipes', description: 'Equipes de campo', routeFile: 'equipes.routes.ts' },
  { prefix: '/api/alocacoes', tag: 'Alocações', description: 'Alocação de equipes', routeFile: 'alocacoes.ts' },
  { prefix: '/api/pessoas', tag: 'Pessoas', description: 'Cadastro de pessoas', routeFile: 'pessoa.routes.ts' },
  { prefix: '/api/clientes', tag: 'Clientes', description: 'CRM de clientes', routeFile: 'clientes.ts' },
  { prefix: '/api/fornecedores', tag: 'Fornecedores', description: 'Cadastro de fornecedores', routeFile: 'fornecedores.ts' },
  { prefix: '/api/projetos', tag: 'Projetos / OS', description: 'Ordens de serviço e etapas', routeFile: 'projetos.ts' },
  { prefix: '/api/cotacoes', tag: 'Cotações', description: 'Banco frio e cotações', routeFile: 'cotacoes.routes.ts' },
  { prefix: '/api/servicos', tag: 'Serviços', description: 'Serviços prestados', routeFile: 'servicos.ts' },
  { prefix: '/api/movimentacoes', tag: 'Movimentações', description: 'Movimentação de estoque', routeFile: 'movimentacoes.ts' },
  { prefix: '/api/historico', tag: 'Histórico', description: 'Histórico de alterações', routeFile: 'historico.ts' },
  { prefix: '/api/nfe', tag: 'NF-e', description: 'Emissão e gestão de NF-e', routeFile: 'nfe.ts' },
  { prefix: '/api/nfse', tag: 'NFS-e', description: 'Notas de serviço eletrônicas', routeFile: 'nfse.routes.ts' },
  { prefix: '/api/empresas', tag: 'Empresas', description: 'Empresas fiscais executoras', routeFile: 'empresas.ts' },
  { prefix: '/api/dashboard', tag: 'Dashboard', description: 'Métricas e indicadores', routeFile: 'dashboard.ts' },
  { prefix: '/api/quadros', tag: 'Quadros', description: 'Quadros prontos', routeFile: 'quadros.routes.ts' },
  { prefix: '/api/kits', tag: 'Kits', description: 'Kits de materiais', routeFile: 'kits.routes.ts' },
  { prefix: '/api/configuracoes', tag: 'Configurações', description: 'Sistema, logos e metas', routeFile: 'configuracao.routes.ts' },
  { prefix: '/api/notificacoes', tag: 'Notificações', description: 'Alertas do usuário', routeFile: 'notificacoes.routes.ts' },
  { prefix: '/api/atendimento-crm', tag: 'Funil CRM', description: 'Leads e funil de atendimento', routeFile: 'atendimentoCrm.routes.ts' },
  { prefix: '/api/whatsapp', tag: 'WhatsApp', description: 'Chat e integração WhatsApp', routeFile: 'whatsapp.routes.ts' },
  { prefix: '/api/contatos-s3e', tag: 'Contatos S3E', description: 'Agenda de contatos internos', routeFile: 'contatosS3e.routes.ts' },
  { prefix: '/api/tarefas-internas', tag: 'Tarefas Internas', description: 'Kanban administrativo', routeFile: 'tarefasInternas.routes.ts' },
  { prefix: '/api/pdf-customization', tag: 'PDF', description: 'Personalização de PDFs', routeFile: 'pdfCustomization.routes.ts' },
  { prefix: '/api/funcionarios', tag: 'Funcionários', description: 'Cadastro de funcionários', routeFile: 'funcionarios.routes.ts' },
  { prefix: '/api/recursos-humanos', tag: 'RH', description: 'Recursos humanos', routeFile: 'recursosHumanos.routes.ts' },
  { prefix: '/api/vales', tag: 'Vales', description: 'Vales e adiantamentos', routeFile: 'vales.routes.ts' },
  { prefix: '/api/beneficios', tag: 'Benefícios', description: 'Benefícios de colaboradores', routeFile: 'beneficios.routes.ts' },
  { prefix: '/api/rh', tag: 'RH Avançado', description: 'Folha, ponto e conferências', routeFile: 'rh.routes.ts' },
  { prefix: '/api/ponto', tag: 'Ponto', description: 'Registro e importação de ponto', routeFile: 'ponto.routes.ts' },
  { prefix: '/api/veiculos', tag: 'Veículos', description: 'Frota', routeFile: 'veiculos.routes.ts' },
  { prefix: '/api/gastos-veiculo', tag: 'Gastos Veículo', description: 'Despesas de frota', routeFile: 'gastosVeiculo.routes.ts' },
  { prefix: '/api/planos', tag: 'Planos', description: 'Planos contratuais', routeFile: 'planos.routes.ts' },
  { prefix: '/api/despesas-fixas', tag: 'Despesas Fixas', description: 'Despesas recorrentes', routeFile: 'despesasFixas.routes.ts' },
  { prefix: '/api/logs', tag: 'Logs', description: 'Auditoria do sistema', routeFile: 'logs.ts' },
  { prefix: '/api/diagnostico', tag: 'Diagnóstico', description: 'Ferramentas de diagnóstico', routeFile: 'diagnostico.ts' },
  { prefix: '/api/ferramentas', tag: 'Ferramentas', description: 'Patrimônio de ferramentas', routeFile: 'ferramentas.routes.ts' },
  { prefix: '/api/kits-ferramenta', tag: 'Kits Ferramenta', description: 'Kits e recibos', routeFile: 'kits-ferramenta.routes.ts' },
  { prefix: '/api/bi', tag: 'BI', description: 'Business intelligence', routeFile: 'bi.routes.ts' },
  { prefix: '/api/resumo-administrativo', tag: 'Resumo Admin', description: 'Painel administrativo', routeFile: 'resumoAdministrativo.routes.ts' },
  { prefix: '/api/financeiro/dre', tag: 'DRE', description: 'Demonstrativo de resultados', routeFile: 'dre.routes.ts' },
  { prefix: '/api/financeiro/fluxo-caixa', tag: 'Fluxo de Caixa', description: 'Fluxo de caixa', routeFile: 'fluxoCaixa.routes.ts' },
  { prefix: '/api/sistema', tag: 'Sistema', description: 'Deploy e sincronização', routeFile: 'sincronizacaoDeploy.routes.ts' },
  { prefix: '/api/movimentacoes-caixa', tag: 'Caixa', description: 'Movimentações de caixa', routeFile: 'movimentacoesCaixa.routes.ts' },
  { prefix: '/api/external/receita', tag: 'Receita WS', description: 'Proxy consulta CNPJ', routeFile: 'receita.routes.ts' },
  { prefix: '/api/webhooks', tag: 'Webhooks', description: 'Integrações externas (WhatsApp)', routeFile: 'webhooks.routes.ts' },
];

/** Rotas declaradas diretamente em app.ts (fora dos routers). */
export const INLINE_APP_ROUTES: Array<{ method: string; path: string; tag: string; summary: string }> = [
  { method: 'GET', path: '/api', tag: 'Sistema', summary: 'Índice de módulos da API' },
  { method: 'GET', path: '/api/health', tag: 'Sistema', summary: 'Health check' },
  { method: 'GET', path: '/health', tag: 'Sistema', summary: 'Health check (alias)' },
  { method: 'GET', path: '/api/configuracoes/logo/{filename}', tag: 'Configurações', summary: 'Servir logo (público)' },
  { method: 'DELETE', path: '/api/configuracoes/logo/{filename}', tag: 'Configurações', summary: 'Excluir logo (admin)' },
  { method: 'GET', path: '/api/materiais/imagem/{filename}', tag: 'Materiais', summary: 'Imagem de material (público)' },
  { method: 'GET', path: '/api/configuracoes/public/logo-login', tag: 'Configurações', summary: 'Logo da tela de login' },
  { method: 'GET', path: '/api/configuracoes/public/portfolio-url', tag: 'Configurações', summary: 'URL do portfólio' },
];
